#pragma once

enum MessageType : unsigned char
{
	// Request codes (client -> server)
	LOGIN_CODE = 200,
	SIGNUP_CODE = 201,
	LOGOUT_CODE = 202,
	GET_ROOMS_CODE = 203,
	GET_PLAYERS_IN_ROOM_CODE = 204,
	JOIN_ROOM_CODE = 205,
	CREATE_ROOM_CODE = 206,
	HIGH_SCORE_CODE = 207,
	PERSONAL_STATS_CODE = 208,
	CLOSE_ROOM_CODE = 209,
	START_GAME_CODE = 210,
	GET_ROOM_STATE_CODE = 211,
	LEAVE_ROOM_CODE = 212,

	LEAVE_GAME_REQUEST_CODE = 213,
	GET_QUESTION_REQUEST_CODE = 214,
	SUBMIT_ANSWER_REQUEST_CODE = 215,
	GET_GAME_RESULTS_REQUEST_CODE = 216,

	// Response codes (server -> client)
	MT_SERVER_UPDATE = 300,
	LOGIN_RESPONSE_CODE = 100,
	SIGNUP_RESPONSE_CODE = 101,
	ERROR_RESPONSE_CODE = 102,
	LOGOUT_RESPONSE_CODE = 103,
	GET_ROOMS_RESPONSE_CODE = 104,
	GET_PLAYERS_IN_ROOM_RESPONSE_CODE = 105,
	JOIN_ROOM_RESPONSE_CODE = 106,
	CREATE_ROOM_RESPONSE_CODE = 107,
	HIGH_SCORE_RESPONSE_CODE = 108,
	PERSONAL_STATS_RESPONSE_CODE = 109,
	CLOSE_ROOM_RESPONSE_CODE = 110,
	START_GAME_RESPONSE_CODE = 111,
	GET_ROOM_STATE_RESPONSE_CODE = 112,
	LEAVE_ROOM_RESPONSE_CODE = 113,
	GET_QUESTION_RESPONSE_CODE = 114,
	LEAVE_GAME_RESPONSE_CODE = 115,
	SUBMIT_ANSWER_RESPONSE_CODE = 116,
	GET_GAME_RESULTS_RESPONSE_CODE = 117
};
